AllCops:
  TargetRubyVersion: 2.6

  Exclude:
    - 'bin/**/*'
    - 'db/*schema.rb'
    - 'db/seeds.rb'
    - 'db/migrate/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'frontend/**/*'

Layout/LineLength:
  Max: 125
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/AbcSize:
  Exclude:
    - db/migrate/*.rb

Metrics/BlockLength:
  Exclude:
    - app/schemas/**/*schema.rb
    - config/routes.rb
    - spec/**/*.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb

Naming/RescuedExceptionsVariableName:
  PreferredName: exception

Style/Documentation:
  Enabled: false

Style/TrailingUnderscoreVariable:
  Enabled: false

Style/GuardClause:
  Enabled: false
